"""comments + updated_at

Revision ID: 4b9a1f574f74
Revises: 8fbb7df1331b
Create Date: 2026-05-22 23:21:20.921377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b9a1f574f74'
down_revision: Union[str, Sequence[str], None] = '8fbb7df1331b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target_type IN ('question', 'answer')", name='ck_comments_target_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comments_target', 'comments', ['target_type', 'target_id', 'created_at'], unique=False)
    op.create_index('idx_comments_user', 'comments', ['user_id'], unique=False)
    op.add_column('answers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('questions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'updated_at')
    op.drop_column('answers', 'updated_at')
    op.drop_index('idx_comments_user', table_name='comments')
    op.drop_index('idx_comments_target', table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
